package misc;

public enum TypeOfCharacter {
	ERROR, TESTRED, TESTBLUE, TESTGREEN, TESTCOLLISION, 
	
	//Boat game
	
	TESTBOAT, TESTFISH1, TESTFISH2, TESTFISH3, TESTFISH4, TESTHSCRAB,
	//Animations
	FISHING1, FISHING2, FISHING3, FISHING4, FISHINGHSC,

	//Crab game
	
	TESTCRAB, TESTCRABFOOD, TESTBADCRAB, TESTBADCRABFOOD, TESTFOOD, 

	
	//Trash game
	
	TESTCHAR, TESTPOOP, TESTTRASH1, TESTTRASH2, TRASH3, TRASH4, TRASHFISH, TESTWALKER, TESTFISH, 
	
	//Animations
	PLAYERWALKUP, PLAYERWALKDOWN, PLAYERWALKLEFT, PLAYERWALKRIGHT,
	PICKUPRIGHTTRASH1, PICKUPRIGHTTRASH2, PICKUPRIGHTTRASH3, PICKUPRIGHTTRASH4,PICKUPRIGHTTRASHFISH, PICKUPRIGHTPOOP,
	PICKUPLEFTTRASH1, PICKUPLEFTTRASH2, PICKUPLEFTTRASH3, PICKUPLEFTTRASH4,PICKUPLEFTTRASHFISH, PICKUPLEFTPOOP
}