package misc;

public enum TypeOfButton {
	STARTSCREEN, DIFFICULTYEASY, DIFFICULTYMED, DIFFICULTYHARD, CHECK, X,
	BLANK,
	BOATGAME, TRASHGAME, CRABGAME, RESET, RESETCONFIRMATION, YES, NO, VICTORYSCREEN1, VICTORYSCREEN2,
	MENU, PAUSESCREEN, RESUME, INSTRUCTIONS, OVERWORLD, ENDSCREEN, TESTINSTRUCTIONSSCREEN,
	INSTRUCTIONSBOAT, INSTRUCTIONSCRAB, INSTRUCTIONSTRASH,
	BOATGAMERULE, BGRF1, BGRF2, BGRF3, BGRF4, BGRHSC, NEXTROUND,
	ERROR, TESTRESET, TESTRESETHOVER, TESTCOLOR, 
}